version: "3"

services:
  employee-service:
    image: sevadasdocker/employee-service
    networks:
      - my-network
    ports: 
      - 8080:8086
    depends_on:
      - database
  database:
    image: mysql:5
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      
networks:
  my-network:
  

  